### ISSUE TITLE
Crashing while attempting to open the saved model

### ISSUE THREAD

**Issue by AlessandroCalio** [morrolinux/simple-ehm#3]
Hi,

I'm using windows as os, anaconda as environment (Python 3.5).
If i try to launch the simple_ehm-runnable.py i'm facing this problem:

```
(sas) C:\Users\Aleassandro\PycharmProjects\sas>python simple_ehm-runnable.py "C:\Users\Aleassandro\Downloads\Lezione di Storia contemporanea 2 - La P
rima Guerra mondiale.mp4"
Traceback (most recent call last):
  File "simple_ehm-runnable.py", line 286, in <module>
    model = tf.keras.models.load_model('model')
  File "C:\Users\Aleassandro\anaconda3\envs\sas\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 218, in load_model
    f = h5py.File(filepath, mode='r')
  File "C:\Users\Aleassandro\anaconda3\envs\sas\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\Aleassandro\anaconda3\envs\sas\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'model', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)
```
If i change this line 
https://github.com/morrolinux/simple-ehm/blob/11e90f9eb25f03209ef9db077da7bf708439666a/simple_ehm-runnable.py#L275 
into :

```
model = tf.keras.models.load_model('model/saved_model.pb')
```

i'm facing this other problem :

```
(sas) C:\Users\Aleassandro\PycharmProjects\sas>python simple_ehm-runnable.py "C:\Users\Aleassandro\Downloads\Lezione di Storia contemporanea 2 - La P
rima Guerra mondiale.mp4"
Traceback (most recent call last):
  File "simple_ehm-runnable.py", line 286, in <module>
    model = tf.keras.models.load_model('model/saved_model.pb')
  File "C:\Users\Aleassandro\anaconda3\envs\sas\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 218, in load_model
    f = h5py.File(filepath, mode='r')
  File "C:\Users\Aleassandro\anaconda3\envs\sas\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\Aleassandro\anaconda3\envs\sas\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

some tips?

**Comment by TheJoin95** [comment]
Hi,

the first error is saying that you don't have the permission to read that dir:
`OSError: Unable to open file (unable to open file: name = 'model', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)`

Did you check your directory rights first? You need to have that directory readable and writable from your execution user.

Meanwhile the second error that you posted on your issue:
`OSError: Unable to open file (file signature not found)`

It's seems like you have something wrong with the model but I'm not sure if it's because of your directory rights or whatever.
Sometimes it happens that the model is being corrupted e.g. `file signature not found`.

I'll suggest you to fresh install (or clone) the repo and try again :)
