### ISSUE TITLE
Crash with particular file

### ISSUE THREAD

**Issue by ElDavoo** [morrolinux/simple-ehm#8]
Using default model
```
Traceback (most recent call last):
  File "simple_ehm-runnable.py", line 292, in <module>
    analyze_track(model, waveform, sample_rate)
  File "simple_ehm-runnable.py", line 73, in timed
    output = f(*args, **kw)
  File "simple_ehm-runnable.py", line 167, in analyze_track
    spectrogram = get_spectrogram(waveform, i, window_size)
  File "simple_ehm-runnable.py", line 108, in get_spectrogram
    spectrogram = tf.signal.stft(equal_length, frame_length=255, frame_step=128)
  File "C:\Users\dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\ops\signal\spectral_ops.py", line 96, in stft
    return fft_ops.rfft(framed_signals, [fft_length])
  File "C:\Users\dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\ops\signal\fft_ops.py", line 141, in _rfft
    return fft_fn(input_tensor, fft_length, Tcomplex=complex_dtype, name=name)
  File "C:\Users\dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\ops\gen_spectral_ops.py", line 1078, in rfft
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\dave\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\framework\ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input dimension 1 must have length of at least 256 but got: 255 [Op:RFFT]
```

[The incriminated file](https://drive.google.com/file/d/1CcIq4w3iRK7lRrfohPCOkWultCtickOR/view?usp=sharing)

**Comment by morrolinux** [comment]
Should be fixed now.
By the way the model doesn't work very well on your professor's voice, I'd suggest you send me some 1 second clips of his voice like instructed in the README for me to improve the training set

**Comment by ElDavoo** [comment]
I wish I had the time to do this... I have tons of material, once the exams period is over I might consider creating a huge training set :P
